name: se
channels:
  - conda-forge
dependencies:
  - python #=3.8
  - numpy
  - pylint
  - scikit-learn
  - pip
  - pandas
  - setuptools
  - matplotlib
  - jupyter
  - tqdm
  - pdoc3
  - cmake
  - gcc_linux-64
  - gxx_linux-64
  - doxygen
  - pip:
    - karma-sphinx-theme
    - sphinx_rtd_theme
    - breathe
    - exhale
  #   - -e file:.